# Generated by Django 5.1.4 on 2025-03-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
