# Generated by Django 5.1.4 on 2025-03-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0004_alter_teststep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='step_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
