# Generated by Django 5.1.4 on 2025-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0005_teststep_step_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_run', 'Not Run')], default='not_run', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='teststep',
            unique_together={('test_case', 'step_number')},
        ),
    ]
