# Generated by Django 5.1.7 on 2025-03-22 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0006_teststep_status_alter_teststep_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_run', 'Not Run')], default='not_run', max_length=10)),
                ('execution_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('test_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='tcms_app.teststep')),
                ('user_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test_step_results', to='tcms_app.usertestcase')),
            ],
        ),
    ]
