# Generated by Django 5.1.7 on 2025-03-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0007_userteststepresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststep',
            name='status',
        ),
    ]
