# Generated by Django 5.1.7 on 2025-03-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0009_remove_bug_test_case_bug_test_case_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseresult',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='tcms_app.usertestcase'),
        ),
    ]
