# Generated by Django 5.1.7 on 2025-03-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0010_alter_testcaseresult_executed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('trivial', 'Trivial')], default='minor', max_length=10),
        ),
    ]
