# Generated by Django 5.1.7 on 2025-03-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0011_bug_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('failed', 'Failed'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
    ]
