# Generated by Django 5.1.7 on 2025-03-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0012_alter_testcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
