# Generated by Django 5.1.7 on 2025-03-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0013_bug_environment_bug_steps_to_reproduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseresult',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='tcms_app.projectteam'),
        ),
    ]
