# Generated by Django 5.1.7 on 2025-03-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0018_alter_bug_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='fix_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bug',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
