# Generated by Django 5.1.7 on 2025-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0019_bug_fix_status_bug_resolution_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('module', 'Module'), ('bug_fix', 'Bug Fix')], default='module', max_length=20),
        ),
    ]
