# Generated by Django 5.1.7 on 2025-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0020_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='fix_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fixed', 'Fixed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
