# Generated by Django 5.1.7 on 2025-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0021_alter_bug_fix_status_alter_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
