# Generated by Django 5.1.7 on 2025-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_app', '0023_task_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
